### ISSUE TITLE
Add support for .graphqlconfig

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/graphql-schema-linter#1]
This would allow the command line tool to run by fetching the schema from the `.graphqlconfig` file.

See: https://github.com/graphcool/graphql-config

**Comment by hegdeashwin** [comment]
See updated link: [here](https://github.com/graphcool/graphql-config)

**Comment by cjoudrey** [comment]
Not sure how relevant this is anymore. Going to close. Feel free to comment/re-open if this is something you care about.
