### ISSUE TITLE
Add plugin to graphql-cli

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/graphql-schema-linter#10]
We should add a plugin to [graphql-cli](https://github.com/graphcool/graphql-cli) to expose the schema linter as `graphql lint schema` or something of that nature.

**Comment by 0xcaff** [comment]
It looks this this is already in `graphql-cli`.

https://github.com/graphql-cli/graphql-cli/blob/7b642f659b318fc64618c3d3b82886a725cd39f9/src/cmds/lint.ts#L1

**Comment by cjoudrey** [comment]
Good point @0xcaff! 😄 Maybe we should document this in the usage section of `README.md`. 🤔

**Comment by cjoudrey** [comment]
Not sure how relevant this is anymore. Going to close. Feel free to comment/re-open if this is something you care about.
