### ISSUE TITLE
add rule for schema indentation

### ISSUE THREAD

**Issue by trashhalo** [cjoudrey/graphql-schema-linter#117]
There doesn't seem to be a rule to fail weird indentation. like some of my types had 2 spaces some 4.

**Comment by trashhalo** [comment]
>Rather than telling the user something is wrong, I prefer just encouraging people to use a tool that will fix the error for them.

I prefer that code not get committed into my teams github that doesn't follow our style guide. Generally how you manage this is fail builds if your eslint fails. Most eslint problems can be dealt with by just running `eslint --fix`.

It looks like I can use prettier with --debug-check to fail builds on style

**Comment by cjoudrey** [comment]
Going to close this issue because it's been inactive for quite some time. Feel free to comment/re-open if this is something you care about.
