### ISSUE TITLE
Support splitting schema into subfolders

### ISSUE THREAD

**Issue by SpaceHeroGuide** [cjoudrey/graphql-schema-linter#125]
If the GraphQL schema is split into multiple files and some files are moved to a subfolder the linter will crash.

If you clone https://github.com/tonyghita/graphql-go-example and try to lint the schema with
```bash
graphql-schema-linter schema/**/*.graphql
```

it will crash:

```bash
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

Error: Query root type must be provided.
    at assertValidSchema (/usr/local/lib/node_modules/graphql-schema-linter/node_modules/graphql/type/validate.js:82:11)
    at validate (/usr/local/lib/node_modules/graphql-schema-linter/node_modules/graphql/validation/validate.js:58:35)
    at validateSchemaDefinition (/usr/local/lib/node_modules/graphql-schema-linter/lib/validator.js:41:41)
    at run (/usr/local/lib/node_modules/graphql-schema-linter/lib/runner.js:66:56)
    at Object.<anonymous> (/usr/local/lib/node_modules/graphql-schema-linter/lib/cli.js:15:32)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

However if you move all files from the folder `schema/type` to `schema` it will work:
```bash
/Users/matthias/Projects/graphql-go-example/schema/film.graphql
1:1  A `PageInfo` object type is required as per the Relay spec.  relay-page-info-spec    
2:1  The object type `Film` is missing a description.             types-have-descriptions 
...
```

I searched the GraphQL documentation to check if they recommend keeping all schema files in the same directory but could not find it.

**Comment by cjoudrey** [comment]
@SpaceHeroGuide thanks for the report. :smile:

I was able to reproduce the issue with the repository you provided.

I'm assuming you are using Bash (let me know if that isn't the case), but here's what I noticed.

When running `graphql-schema-linter schema/**/*.graphql` in Bash, `schema/**/*.graphql` is expanded to:

```
[ 'schema/type/film.graphql',
  'schema/type/length_unit.graphql',
  'schema/type/mass_unit.graphql',
  'schema/type/person.graphql',
  'schema/type/planet.graphql',
  'schema/type/species.graphql',
  'schema/type/starship.graphql',
  'schema/type/time.graphql',
  'schema/type/vehicle.graphql' ]
```

You can try this out yourself using `ls`:

```
$ ls -la schema/**/*.graphql
-rw-r--r--  1 cjoudrey  wheel   965 Apr 10 10:19 schema/type/film.graphql
-rw-r--r--  1 cjoudrey  wheel   961 Apr 10 10:19 schema/type/length_unit.graphql
-rw-r--r--  1 cjoudrey  wheel   409 Apr 10 10:19 schema/type/mass_unit.graphql
-rw-r--r--  1 cjoudrey  wheel  1619 Apr 10 10:19 schema/type/person.graphql
-rw-r--r--  1 cjoudrey  wheel  1349 Apr 10 10:19 schema/type/planet.graphql
-rw-r--r--  1 cjoudrey  wheel  1389 Apr 10 10:19 schema/type/species.graphql
-rw-r--r--  1 cjoudrey  wheel  1723 Apr 10 10:19 schema/type/starship.graphql
-rw-r--r--  1 cjoudrey  wheel    44 Apr 10 10:19 schema/type/time.graphql
-rw-r--r--  1 cjoudrey  wheel  1508 Apr 10 10:19 schema/type/vehicle.graphql
```

As you can see a bunch of files were omitted, specifically the ones in `schema/*.graphql`.

There appears to be two solutions to fix this.

You can continue letting Bash expand the glob, and add the missing paths using: `graphql-schema-linter schema/*.graphql schema/**/*.graphql`

Or alternatively you can use: `graphql-schema-linter "schema/**/*.graphql"`. By wrapping the glob in double quotes, Bash doesn't expand it and instead the glob is _properly_ expanded in JS land by [`node-glob`](https://github.com/isaacs/node-glob).

If this becomes a common source of confusion, I may mention something about it in the `README.md`.

Feel free to re-open this issue if you think there is more to it. 😄

**Comment by SpaceHeroGuide** [comment]
Thank you!

Wrapping the glob in double quotes worked!
