### ISSUE TITLE
Parser Syntax Error: implements with multiple interfaces

### ISSUE THREAD

**Issue by n1ru4l** [cjoudrey/graphql-schema-linter#137]
This is valid syntax:
```gql
type Artist implements Foo, Bar {
  id: ID!
}
```

The script fails with the following command: `Syntax Error: Unexpected Name "Bar"  undefined`

Version: `graphql-schema-linter@0.1.6`

**Comment by cjoudrey** [comment]
Hello @n1ru4l,

This is indeed valid syntax, but has been deprecated as of version `0.13.0` of GraphQL.js. You may use this deprecated syntax by providing the `--old-implements-syntax` option.

Alternatively, you can use the new syntax:

```graphql
type Artist implements Foo & Bar {
  id: ID!
}
```

You can find more information about this here: https://github.com/graphql/graphql-js/pull/1169
