### ISSUE TITLE
Add a rule that requires that all types are sorted alphabetically

### ISSUE THREAD

**Issue by gajus** [cjoudrey/graphql-schema-linter#143]

**Comment by cjoudrey** [comment]
Thanks for opening the issue @gajus! :smile:

I can understand why someone might want this, but I don't feel comfortable adding this to the default set of rules.

If I were you, I would start with [writing a custom rule](https://github.com/cjoudrey/graphql-schema-linter#customizing-rules) for this.

Writing this rule to support cases where the schema is divided into multiple files might be tricky as the code currently [merges all the files together](https://github.com/cjoudrey/graphql-schema-linter/blob/b309eedf8f0d93db0bcfeb9974e0b42bc1a1ca25/src/configuration.js#L69-L70). The `configuration` object does expose a [`SourceMap`](https://github.com/cjoudrey/graphql-schema-linter/blob/6f748d1b24428256abecd90d5d2e8947f86cb6f8/src/source_map.js) that allows you to map a line from the merged schema back to the individual file.

**Comment by pelhage** [comment]
I'm currently trying to write a custom rule but ran into some issues. @gajus did you end up attempting this?

**Comment by gajus** [comment]
No, ended up building an adhoc tool at the time to do this using AST.

**Comment by cjoudrey** [comment]
> I'm currently trying to write a custom rule but ran into some issues.

@pelhage what issues did you run into?

**Comment by pelhage** [comment]
@cjoudrey I'm unable to test my custom rules in my project

I have a directory structure like:

```
rules/
  types_are_capitalized.js
src/
  ...
  schema.graphql
```

And I'm trying to run linting via an npm script

```
  "scripts": {
  ...
  "lint:rules": "graphql-schema-linter --custom-rule-paths rules/types_are_capitalized.js src/schema.graphql",
  ...
```

even `rules/*.js` didn't work for `--custom-rule-paths`

I tried throwing an error from within my custom rule, but I'm not seeing any output. I'm just a bit unsure what I'm missing here to be able to successfully run custom rules

**Comment by cjoudrey** [comment]
That's really strange @pelhage. Do you mind sharing the contents of `types_are_capitalized.js` so that I can try it out?

So long as `types_are_capitalized.js` exports a function, it should get called. There are some dummy custom rules in the [`test/fixtures`](https://github.com/cjoudrey/graphql-schema-linter/tree/master/test/fixtures/custom_rules) folder.

**Comment by gajus** [comment]
For what it is worth, I have implemented this requirement in https://github.com/gajus/format-graphql.

**Comment by cjoudrey** [comment]
Going to close this issue because it's been inactive for quite some time. Feel free to comment/re-open if this is something you care about.
