### ISSUE TITLE
Add ability to configure via dot file .graphql-schema-linter

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/graphql-schema-linter#16]
Rather than have to always configure the linter via command line options, it could be useful to have a dot file at the root of a project to configure what rules should be used.

**Comment by goldcaddy77** [comment]
Per our convos, we should also consider a package.json config key to avoid cluttering the project's root folder.

**Comment by cjoudrey** [comment]
I wasn't aware this was something people were doing now. I wouldn't mind support that too if it's a convention people have been adopting.

**Comment by goldcaddy77** [comment]
There have been a lot of discussions lately, especially on the [prettier](https://github.com/prettier/prettier) project:

- https://github.com/prettier/prettier/issues/98
- https://github.com/prettier/prettier/pull/2434

A number of projects have started using [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) project to do the config management.

**Comment by cjoudrey** [comment]
TIL -- Thanks for sharing those lines @goldcaddy77. I wouldn't mind using `cosmicconfig`. 

I think we should support `.graphqlconfig` too as per #1.

**Comment by cjoudrey** [comment]
This was fixed by #26
