### ISSUE TITLE
Unknown directive "aws_subscribe".  invalid-graphql-schema

### ISSUE THREAD

**Issue by yvele** [cjoudrey/graphql-schema-linter#165]
Looks like `v0.2.0` is breaking with custom directives

> Unknown directive "aws_subscribe".  invalid-graphql-schema

I can't see in the documentation how to customize `invalid-graphql-schema` rule to enable custom directives like `@aws_subscribe` for AWS AppSync. Is there a way?

```graphql
type Subscription {
    addedPost: Post
    @aws_subscribe(mutations: ["addPost"])
    updatedPost: Post
    @aws_subscribe(mutations: ["updatePost"])
    deletedPost: Post
    @aws_subscribe(mutations: ["deletePost"])
}
```

Reference: https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html

PS: By the way thank you for you tool 👍 and I suggest you to use git tags and GitHub releases every time you release a new version https://github.com/cjoudrey/graphql-schema-linter/releases

**Comment by cjoudrey** [comment]
Hi @yvele, thanks for the feedback and opening this issue. 😄 

This is an interesting issue. Have you considered including a directive definition at the top of your schema or in a separate file? Something like this:

```graphql
directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION
```

By doing this, the linter error would go away and your schema would be _complete_ which might make it easier for someone new to add a `@aws_subscribe` elsewhere.

In an ideal world, it would be great if AWS AppSync provided an SDL file with all the custom directives it supports, that way you could either extend the schema with it or simply pass both files to `graphql-schema-linter`.

An alternative solution would be to customize `invalid-graphql-schema` as you suggested, but I'm hesitant because it encourages people to write incomplete schemas.

Any further thoughts?

> and I suggest you to use git tags and GitHub releases every time you release a new version

:+1: That's a great point. I completely forgot to do this since the beginning. 😢I'll see if I can retroactively create them based on commit data. In the meantime, [CHANGELOG.md](https://github.com/cjoudrey/graphql-schema-linter/blob/1cc6ab9a7e2cf529a99a329fe2a4a516851184ba/CHANGELOG.md) might be helpful.

**Comment by yvele** [comment]
I don't want to alter my schema just to make the linter pass.. That's not a good workaround

Why isn't possible to add custom rules?

This is breaking for me, I think I'm gonna stick with 0.1.6

**Comment by cjoudrey** [comment]
Hey @yvele, I added some more thoughts about this here: https://github.com/cjoudrey/graphql-schema-linter/pull/171#issuecomment-468121820. You might be interested.

> AWS doesn't accepts `directive` anyway

Just to clarify, earlier I didn't mean you had to add the directive definitions to your schema, they could live in a separate file then you can use: `graphql-schema-linter aws_appsync.graphql schema.graphql`.

**Comment by yvele** [comment]
To me adding an extra GraphQL file **only** for the linter is not acceptable, it complexify the global understanding of the code base.. make directive ambiguous.. To me this is only about configuring the linter, and should be an explicit linter rule, in a linter config file (or parameter, I don't know).

About https://github.com/cjoudrey/graphql-schema-linter/pull/171#issuecomment-468121820 I think that adding a specific`--aws-appsync` edge case to the linter is too specific to AWS.. what about one day Azure or Google Cloud platform will also make specific thinks? Don't you wan't to have a generic interface? Customizable for all providers, frameworks, etc? That's how most linter works, eslint, etc..

**Comment by jamesgraham** [comment]
We've also just run into this and other false-positives:

`74:14  Unknown type "AWSDateTime".        invalid-graphql-schema`

What's the current workaround?

**Comment by cjoudrey** [comment]
> About [#171 (comment)](https://github.com/cjoudrey/graphql-schema-linter/pull/171#issuecomment-468121820) I think that adding a specific`--aws-appsync` edge case to the linter is too specific to AWS.

Agreed, I kinda want to stick with `graphql-schema-linter linter/aws_appsync.graphql schema.graphql` for now and see how it plays out.

> What's the current workaround

Currently the workaround would be to provide the AWS AppSync type definitions when linting your schema. These definitions can live in a separate file than your schema.

Create a file named `aws_appsync.graphql`, for example:

```graphql
# https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html#appsync-defined-scalars

"""
The AWSDate scalar type represents a valid extended ISO 8601 Date string. In other words, this scalar type accepts date strings of the form YYYY-MM-DD. This scalar type can also accept time zone offsets. For example, 1970-01-01Z, 1970-01-01-07:00 and 1970-01-01+05:30 are all valid dates. The time zone offset must either be Z (representing the UTC time zone) or be in the format ±hh:mm:ss. The seconds field in the timezone offset will be considered valid even though it is not part of the ISO 8601 standard.
"""
scalar AWSDate

"""
The AWSTime scalar type represents a valid extended ISO 8601 Time string. In other words, this scalar type accepts time strings of the form hh:mm:ss.sss. The field after the seconds field is a nanoseconds field. It can accept between 1 and 9 digits. The seconds and nanoseconds fields are optional (the seconds field must be specified if the nanoseconds field is to be used). This scalar type can also accept time zone offsets.

For example, 12:30Z, 12:30:24-07:00 and 12:30:24.500+05:30 are all valid time strings.

The time zone offset must either be Z (representing the UTC time zone) or be in the format hh:mm:ss. The seconds field in the timezone offset will be considered valid even though it is not part of the ISO 8601 standard.
"""
scalar AWSTime

"""
The AWSDateTime scalar type represents a valid extended ISO 8601 DateTime string. In other words, this scalar type accepts datetime strings of the form YYYY-MM-DDThh:mm:ss.sssZ. The field after the seconds field is a nanoseconds field. It can accept between 1 and 9 digits. The seconds and nanoseconds fields are optional (the seconds field must be specified if the nanoseconds field is to be used). The time zone offset is compulsory for this scalar. The time zone offset must either be Z (representing the UTC time zone) or be in the format ±hh:mm:ss. The seconds field in the timezone offset will be considered valid even though it is not part of the ISO 8601 standard.
"""
scalar AWSDateTime

"""
The AWSTimestamp scalar type represents the number of seconds that have elapsed since 1970-01-01T00:00Z. Timestamps are serialized and deserialized as numbers. Negative values are also accepted and these represent the number of seconds till 1970-01-01T00:00Z.
"""
scalar AWSTimestamp

"""
The AWSEmail scalar type represents an Email address string that complies with RFC 822. For example, username@example.com is a valid Email address.
"""
scalar AWSEmail

"""
The AWSJSON scalar type represents a JSON string that complies with RFC 8259.

Maps like {\"upvotes\": 10}, lists like [1,2,3], and scalar values like \"AWSJSON example string\", 1, and true are accepted as valid JSON. They will automatically be parsed and loaded in the resolver mapping templates as Maps, Lists, or Scalar values rather than as the literal input strings. Invalid JSON strings like {a: 1}, {'a': 1} and Unquoted string will throw GraphQL validation errors.
"""
scalar AWSJSON

"""
The AWSURL scalar type represents a valid URL string. The URL may use any scheme and may also be a local URL (Ex: <http://localhost/>). URLs without schemes are considered invalid. URLs which contain double slashes are also considered invalid.
"""
scalar AWSURL

"""
The AWSPhone scalar type represents a valid Phone Number. Phone numbers are serialized and deserialized as Strings. Phone numbers provided may be whitespace delimited or hyphenated. The number can specify a country code at the beginning but this is not required.
"""
scalar AWSPhone

"""
The AWSIPAddress scalar type represents a valid IPv4 or IPv6 address string.
"""
scalar AWSIPAddress

"""
Specify multiple mutations which trigger a subscription.
"""
directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION
```

Then when running `graphql-schema-linter` specify this file, for example:

```
graphql-schema-linter schema/*.graphql aws_appsync.graphql
```

One problem you might run into is the linter will complain about unused types, for example:

```
aws_appsync.graphql
8:1  The type `AWSTime` is defined in the schema but not used anywhere.       defined-types-are-used
```

I would comment out the types you don't use. This isn't great, but it works for now.

**Comment by yvele** [comment]
Thanks @cjoudrey for the suggestion, it's working nicely and it's clean 👍

**Comment by taouichaimaa** [comment]
> Hi @yvele, thanks for the feedback and opening this issue. 😄
> 
> This is an interesting issue. Have you considered including a directive definition at the top of your schema or in a separate file? Something like this:
> 
> ```graphql
> directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION
> ```
> 
> By doing this, the linter error would go away and your schema would be _complete_ which might make it easier for someone new to add a `@aws_subscribe` elsewhere.
> 
> In an ideal world, it would be great if AWS AppSync provided an SDL file with all the custom directives it supports, that way you could either extend the schema with it or simply pass both files to `graphql-schema-linter`.
> 
> An alternative solution would be to customize `invalid-graphql-schema` as you suggested, but I'm hesitant because it encourages people to write incomplete schemas.
> 
> Any further thoughts?
> 
> > and I suggest you to use git tags and GitHub releases every time you release a new version
> 
> 👍 That's a great point. I completely forgot to do this since the beginning. 😢I'll see if I can retroactively create them based on commit data. In the meantime, [CHANGELOG.md](https://github.com/cjoudrey/graphql-schema-linter/blob/1cc6ab9a7e2cf529a99a329fe2a4a516851184ba/CHANGELOG.md) might be helpful.
> 
> **Edit:** I've started re-adding them retroactively. Thanks for calling this out. 😄

Hi @cjoudrey , I realize this thread has been closed but I'm having the same problem, except when I define the @aws_iam or any of the pools used in mutation like that, the ones used on objects(types) generate the 'trying to redefine directive ' error. Any thoughts?
