### ISSUE TITLE
Option to Disable Specific Default Rules

### ISSUE THREAD

**Issue by reskin89** [cjoudrey/graphql-schema-linter#232]
Currently there is no option to disable certain rules, only to add specific custom rules or use specific rules.  There are a great deal of rules included by default (which is great!) but sometimes some of them would be nice to have off for a short period of time, just to more easily isolate others.

i.e. I was running a test where my schema has no relay in it by default, and I merely wanted to *exclude* the relay validation rules, and the only way to work around this, was to move the files out of the default rules folder for the time being.

**Comment by cjoudrey** [comment]
Thanks for opening this issue @reskin89. 

The `--except ...` option was meant to solve this problem. A while back, I had marked it as deprecated, but I'm thinking it might make sense to keep it for just this reason.

Alternatively, you can use the `--rules ...` option, but it comes with the downside of needing to specify all the rules you want to enable except for the one you want to disable. It feels a bit clunky.

Let me know if that solves your issue.

**Comment by reskin89** [comment]
—except seems like it’d be perfect, especially as the tool evolves and potentially has more rules as the spec evolves

**Comment by cjoudrey** [comment]
Awesome! 😄 I'll close this then.
