### ISSUE TITLE
Add a rule that validates all interface fields are sorted alphabetically

### ISSUE THREAD

**Issue by hipper** [cjoudrey/graphql-schema-linter#258]
Couple of A->Z rules were already added to the project, which is great. We have:

- type-fields-sorted-alphabetically
- input-object-fields-sorted-alphabetically

One that lacks validation at the moment, however, is an interface type.

Propose to add `interface-fields-sorted-alphabetically`

**Comment by cjoudrey** [comment]
Thanks for opening this issue @hipper.

I must've forgotten this when I implemented the sorted object type fields.

If you'd like to open a pull request for this that'd be super helpful. You could create a new rule called `interface-fields-sorted-alphabetically` and the implementation will be very similar to `type-fields-sorted-alphabetically`. You could probably also copy that rules' tests.

**Comment by hipper** [comment]
Thanks @cjoudrey, I've raised a PR to fix this.
