### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/graphql-schema-linter#31]
Some examples:

- [thoughtbot/factory_girl_rails/CONTRIBUTING.md](https://github.com/thoughtbot/factory_girl_rails/blob/dca37318f34b6ac102df70a162c4c5cbd4fc840a/CONTRIBUTING.md)

**Comment by hegdeashwin** [comment]
@cjoudrey This is address in this [PR](https://github.com/cjoudrey/graphql-schema-linter/pull/52)
