### ISSUE TITLE
Put prettier config settings in package.json

### ISSUE THREAD

**Issue by goldcaddy77** [cjoudrey/graphql-schema-linter#32]
...so that all of our editors are using the same settings.  Blocked by: https://github.com/prettier/prettier/issues/2589

**Comment by cjoudrey** [comment]
I think we can do this now! :tada:

https://github.com/prettier/prettier/releases/tag/1.6.0

**Comment by goldcaddy77** [comment]
Done https://github.com/cjoudrey/graphql-schema-linter/pull/43
