### ISSUE TITLE
Add rule to detect trailing comma (cfr. comma-dangle from eslint)

### ISSUE THREAD

**Issue by entropitor** [cjoudrey/graphql-schema-linter#49]
Is it possible to add a rule that detects if there is a trailing comma and errors if not? 

(Like the comma-dangle rule in eslint)

**Comment by cjoudrey** [comment]
Hi @entropitor thanks for opening the issue. 😄 

Just to clarify, where exactly would you want to enforce trailing comma? Can you provide an example?

Thanks!

**Comment by entropitor** [comment]
```graphql
type User {
  email: String!,
  name: String!,
}```

But I'm not sure if the comma is obligated even. It could also be a rule to disable these comma's or not.

It would be nice to enforce it to be consistent though

**Comment by cjoudrey** [comment]
Gotcha!

> But I'm not sure if the comma is obligated even.

The comma is optional. From what I've seen most people omit them.

I think this belongs in `prettier` as it is something that can automatically be fixed and is something that affects both `.graphql` schema files and query files. It isn't limited to schema definitions.

What do you think?

**Comment by cjoudrey** [comment]
@entropitor I'm going to close this as I feel this should be handled by `prettier`. Feel free to re-open if you disagree.
