### ISSUE TITLE
Descriptions as strings

### ISSUE THREAD

**Issue by cjoudrey** [cjoudrey/graphql-schema-linter#77]
As per https://github.com/graphql/graphql-js/pull/927, descriptions are now strings instead of comments in the SDL.

In order to provide a graceful upgrade path, we could bump `graphql-js` and add a new configuration option called `--comments-as-descriptions` that would toggle `buildASTSchema`'s `{commentDescriptions: true}`.

**Comment by adampash** [comment]
As a new user, this is a blocker for me (I'm using the latest `graphql-js` but can't write descriptions with strings if I'm using this linter). Looking into it, it looks like the latest release of `graphql-js` has removed the `getDescription` export, but it's been [merged back into master](https://github.com/graphql/graphql-js/pull/1165). It seems like once `graphql-js` cuts a new release, `graphql-schema-linter` could be updated?

**Comment by cjoudrey** [comment]
@adampash thanks for the feedback. Now that the changes were shipped in `graphql-js` I think this becomes even more important.

I believe we could also temporarily run off `graphql-js`'s `master` branch if a release doesn't come shortly.

**Comment by cjoudrey** [comment]
@adampash just wanted to give you an update. I'm working on this at the moment and should be available in next release. 😁

**Comment by cjoudrey** [comment]
This has shipped in `0.1.0`.

**Comment by adampash** [comment]
Thanks @cjoudrey!!
