### ISSUE TITLE
Error: Type abc was defined more than once.

### ISSUE THREAD

**Issue by ajay-nagarro** [cjoudrey/graphql-schema-linter#87]
Hi,

I am facing some strange issue when running linter on multiple graphql schema. I have multiple schema in my directory. I can have same type/enum there when we consider two schema files. If one schema has "abc" type then second schema can also have same type.

This is my configuration to run linter:

```
  "lint-staged": {
    "modules/*/graphql-schema/consolidate.gql": [
      "graphql-schema-linter"
    ]
  },
  "graphql-schema-linter": {
    "rules": [
      "defined-types-are-used"
    ]
  } 

```

In case of, for example type `abc` exists in two schema files then I am getting an error when running linting. Can we avoid this by defining any rules ?

```
Error: Type "abc" was defined more than once.
at buildASTSchema (C:\Users\ajaysaini\AppData\Local\Yarn\config\global
ode_modules\graphql\utilities\buildASTSchema.js:111:17)
at validateSchemaDefinition (C:\Users\ajaysaini\AppData\Local\Yarn\config\global
ode_modules\graphql-schema-linter\lib\validator.js:18:51)
at run (C:\Users\ajaysaini\AppData\Local\Yarn\config\global
ode_modules\graphql-schema-linter\lib\runner.js:51:54)
at Object.<anonymous> (C:\Users\ajaysaini\AppData\Local\Yarn\config\global
ode_modules\graphql-schema-linter\lib\cli.js:15:32)
at Module._compile (module.js:573:30)
at Object.Module._extensions..js (module.js:584:10)
at Module.load (module.js:507:32)
at tryModuleLoad (module.js:470:12)
at Function.Module._load (module.js:462:3)
× graphql-schema-linter found some errors. Please fix them and try committing again.
at Function.Module.runMain (module.js:609:10)

```

**Comment by cjoudrey** [comment]
It sounds like have two schemas that share types.

If this is the case, you'll want to run `graphql-schema-linter` once for each schema.

When you provide multiple `.graphql` files to `graphql-schema-linter` it assumes your schema is divided into multiple files and it will concatenate them all together.

Running `graphql-schema-linter schema1.graphql schema2.graphql` will concatenate `schema1.graphql` with `schema2.graphql` which will lead to some types being defined twice in your case.

Let me know if I misunderstood your issue. 😀

**Comment by ajay-nagarro** [comment]
Yes, Running `graphql-schema-linter` once for each schema is OK. I have pre commit hooks where I am validating all schema using this regex in package.json. So there could be multiple schemas and there could be same type in some schema.

```
  "lint-staged": {
    "modules/*/graphql-schema/consolidate.gql": [
      "graphql-schema-linter"
    ]
  },
  "graphql-schema-linter": {
    "rules": [
      "defined-types-are-used"
    ]
  } 
```

Can we do something with this regex `modules/*/graphql-schema/consolidate.gql` so `graphql-schema-linter` will run once for each schema.

**Comment by ajay-nagarro** [comment]
Hey @cjoudrey can you please suggest any workaround on this ?

**Comment by cjoudrey** [comment]
Before adding a new option flag to support multiple schemas to `graphql-schema-linter` I'd like to make sure this is a common use-case as it will add complexity.

In the meantime a workaround could be to define them each individually in `lint-staged`:

```json
  "lint-staged": {
    "modules/schema_1/graphql-schema/consolidate.gql": [
      "graphql-schema-linter"
    ],
    "modules/schema_2/graphql-schema/consolidate.gql": [
      "graphql-schema-linter"
    ]
  },
```

**Comment by cjoudrey** [comment]
I added some clarity around `lint-staged` to the `README` in https://github.com/cjoudrey/graphql-schema-linter/commit/a23434eef7a56e100911809a875daac33df7520c to cover the above issue.

I'm going to close this issue for now. Feel free to re-open if you think this is still a problem.

**Comment by glenndevenish** [comment]
I just bumped into an issue with types being defined more than once:

```
It looks like you may have hit a bug in graphql-schema-linter.

It would be super helpful if you could report this here: https://github.com/cjoudrey/graphql-schema-linter/issues/new

Error: Type "Address" was defined more than once.
```

It is defined more than once, not sure what the 'bug in graphql-schema-linter' is though
